import { Inter } from 'next/font/google'
import './globals.css'
import Home from './page'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'MyApp',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
<body className={[inter.className, "bg-gray-100"].join(' ')}>
        <Home>{children}</Home>
      </body>
    </html>
  )
}